apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbservice
  labels:
    app: dbservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbservice
  template:
    metadata:
      labels:
        app: dbservice
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
          - containerPort: 3306
        envFrom:
          - configMapRef:
              name: mysql-config
          - secretRef:
              name: mysql-secret
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
          - name: mysql-init
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-init
          configMap:
            name: mysql-initdb
---
apiVersion: v1
kind: Service
metadata:
  name: dbservice
spec:
  type: ClusterIP
  selector:
    app: dbservice
  ports:
    - port: 3306
      targetPort: 3306
