apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadminservice
  labels:
    app: phpmyadminservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadminservice
  template:
    metadata:
      labels:
        app: phpmyadminservice
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
          - containerPort: 80
        env:
          - name: PMA_HOST
            value: dbservice
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadminservice
spec:
  type: NodePort
  selector:
    app: phpmyadminservice
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30801
